# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    active_app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ['@user_repository', '@fos_user.util.token_generator.default']
    active_app.client_manager:
        class: AppBundle\Manager\ClientManager
        arguments: ['@client_repository']
    app.client_voter:
        class:  AppBundle\Security\ClientVoter
        tags:
          - { name: security.voter }
        public: false
    mail_manager:
        class:     AppBundle\Manager\MailManager
        arguments: ["@mailer", "@twig"]
